//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeContact
    {
        public long employeeContactId { get; set; }
        public long employeeId { get; set; }
        public string contactType { get; set; }
        public string description { get; set; }
        public string createIP { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public string modifyIP { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string modifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
