//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Employee1 = new HashSet<Employee>();
            this.EmployeeContacts = new HashSet<EmployeeContact>();
            this.VolunteerTimeSheets = new HashSet<VolunteerTimeSheet>();
        }
    
        public long employeeId { get; set; }
        public byte[] ssn { get; set; }
        public string cjis { get; set; }
        public string networkId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string suffix { get; set; }
        public string formerName { get; set; }
        public string preferredName { get; set; }
        public byte[] sex { get; set; }
        public string maritalStatus { get; set; }
        public byte[] dob { get; set; }
        public string birthPlace { get; set; }
        public byte[] dLicense { get; set; }
        public byte[] passport { get; set; }
        public string isActive { get; set; }
        public string terminationCode { get; set; }
        public string veteran { get; set; }
        public string division { get; set; }
        public string department { get; set; }
        public string employeeType { get; set; }
        public string createIP { get; set; }
        public System.DateTime createDate { get; set; }
        public string createdBy { get; set; }
        public string modifyIP { get; set; }
        public Nullable<System.DateTime> modifyDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<long> supervisorId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContact> EmployeeContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VolunteerTimeSheet> VolunteerTimeSheets { get; set; }
    }
}
