//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC1.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VolunteerTimeSheetData
    {
        public long VTimeSheetDataId { get; set; }
        public long UserTimeSheetId { get; set; }
        public System.DateTime WorkDate { get; set; }
        public int Hours { get; set; }
        public string Sec_Unit { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual VolunteerTimeSheet VolunteerTimeSheet { get; set; }
    }
}
